travis:
  secure:
    BINSTAR_TOKEN: M//G/+nGEFeB2LwOfvvuDw0HRio40TFaA/c6B3pRTFCczdjWXpjD6T1GYdVzvA+YhUfSXJF0wGkZFAAdx/LmtHphce56fGsiwqLPvmWeUm5KWnVa63IbziEqFx0Fr5q0btZxwuIYedNlYDUVUve3QQxG9M+NcKBtbuyWszYxty/fIX09OtA+b4s8L6T4fcVe9oB8gPtF0upRA8DNHb4yNzll8l1SUqhzCrE7GTiDY4fbaOH7q9+P9XOxp93mcAaUaJWNaNitJRA3Gq5oNBq3wdxUcu3D+ru8TDO8TH8RrgEK1RDK2zmfxSzUS2cLh58F62hzxdajLPUO0aZSNysKf8YECk0qrFi/6bW+uqld3qezNA+Y2AdeYFvKE4y2BFenOuCClhd2fdHbUStgzV+cvuYbVBYp/GdnJZhACzlevEPYXzorwiCIFcO5By6XK+vfcjWqaVLmSmtqI2Okt7UqAj6WWSj+NXWsEyudRID+hr07xKdvuL1apr4whHfx+cf8ot64J9jhRgAbtpSZSSNVxLJuj0Nioe6w3h0KNQ6irpj3UGnKrQapCIFfVVPMP2NtATBfED1h3O6iX3aFy3kzvOUwtjRXZ3+4l4XfEwu/QZ+BYJIpD3C3ilJ3bWm1JFoUsXYIIWeLHPVi3bc5/68A1ru4YrxPwkG393h/MWDVMmk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
